const data = [ { name: "Towel", price: 200, quantity: 18, category: "Men" },
  { name: "Bedsheet", price: 500, quantity: 12, category: "Women" },
  { name: "Pillow Cover", price: 150, quantity: 25, category: "Kids" },
  { name: "Curtains", price: 700, quantity: 8, category: "Men" },
  { name: "Blanket", price: 1200, quantity: 30, category: "Women" },
  { name: "Mattress", price: 3000, quantity: 5, category: "Kids" },
  { name: "Quilt", price: 2500, quantity: 15, category: "Men" },
  { name: "Cushion", price: 350, quantity: 10, category: "Women" },
  { name: "Rug", price: 1800, quantity: 22, category: "Kids" },
  { name: "Table Cloth", price: 600, quantity: 9, category: "Men" },
  { name: "Sofa Cover", price: 850, quantity: 16, category: "Women" },
  { name: "Shower Curtain", price: 750, quantity: 18, category: "Kids" },
  { name: "Door Mat", price: 300, quantity: 28, category: "Men" },
  { name: "Bathrobe", price: 2000, quantity: 7, category: "Women" },
  { name: "Hand Towel", price: 100, quantity: 50, category: "Kids" },
  { name: "Face Towel", price: 120, quantity: 45, category: "Men" },
  { name: "Napkins", price: 90, quantity: 35, category: "Women" },
  { name: "Carpet", price: 5000, quantity: 4, category: "Kids" },
  { name: "Window Blinds", price: 2200, quantity: 12, category: "Men" },
  { name: "Table Runner", price: 700, quantity: 18, category: "Women" },
  { name: "Duvet", price: 4500, quantity: 10, category: "Kids" },
  { name: "Silk Pillowcase", price: 900, quantity: 20, category: "Men" },
  { name: "Fleece Blanket", price: 1800, quantity: 14, category: "Women" },
  { name: "Weighted Blanket", price: 3200, quantity: 6, category: "Kids" },
  { name: "Linen Sheets", price: 4000, quantity: 9, category: "Men" },
];
